apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-service
  namespace: media-server
  labels:
    app: flaresolverr
spec:
  selector:
    app: flaresolverr
  ports:
  - name: http
    port: 8191
    targetPort: 8191
    nodePort: 30191
    protocol: TCP
  type: NodePort
