apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
  namespace: media-server
  labels:
    app: prowlarr
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      port: 9696
      targetPort: 9696
      nodePort: 30696
      protocol: TCP
  type: NodePort
