apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: media-server
  labels:
    app: radarr
spec:
  selector:
    app: radarr
  ports:
  - name: http
    port: 7878
    targetPort: 7878
    nodePort: 30878
    protocol: TCP
  type: NodePort
