apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: photography-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: photography-server/frontend:latest
          imagePullPolicy: Never  # For local development
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://api-service:8000"
          command: [ "npm", "run", "dev" ]
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
      initContainers:
        - name: wait-for-api
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nc -z api-service 8000; do echo waiting for api; sleep 2; done;' ]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: photography-server
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: NodePort  # or LoadBalancer if you have external access
