apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/photography-server/photos
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - marlanserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-pvc
  namespace: photography-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage
