apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: media-server
  labels:
    app: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          ports:
            - containerPort: 5055
              name: http
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "UTC"
          volumeMounts:
            - name: config
              mountPath: /app/config
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config-pvc
