apiVersion: v1
kind: Service
metadata:
  name: jellyseerr-service
  namespace: media-server
  labels:
    app: jellyseerr
spec:
  selector:
    app: jellyseerr
  ports:
  - name: http
    port: 5055
    targetPort: 5055
    nodePort: 30055
    protocol: TCP
  type: NodePort
