apiVersion: v1
kind: PersistentVolume
metadata:
  name: wedding-photos-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    namespace: wedding
    name: photos-pvc
  hostPath:
    path: /mnt/wedding/photos
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-pvc
  namespace: wedding
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
