apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: media-server
  labels:
    app: sonarr
spec:
  selector:
    app: sonarr
  ports:
    - name: http
      port: 8989
      targetPort: 8989
      nodePort: 30989
      protocol: TCP
  type: NodePort
